import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Box, Container, Flex, Spacer } from "@chakra-ui/react";
import NavBar from "../sections/navBar";
import Hero from "../sections/hero";
import Carousel from "../sections/carousel";
import { getEntries } from "../services/contentful";

export async function getStaticProps({}) {
  const post = await getEntries({
    content_type: "carousel",
    include: 10,
  });

  return {
    props: {
      landscapeCarousel: post.items[0].fields,
    },
  };
}

const Home: NextPage = ({ landscapeCarousel }: { landscapeCarousel: any }) => {
  return (
    <div>
      <Head>
        <title>Contenful Chakra</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <Container mb="9">
        <Hero
          title="Grasshoppers Academy Content Studio"
          description="Grasshoppers Academy Content Studio (GACS) is an initiative that allows students to build (partial) dynamic websites for real clients."
          cta={{ label: "Documentation", href: "documentation" }}
          image={{ src: "ontwikkelen-jstack.jpg", alt: "ontwikkelen jstack" }}
        />
        <Carousel
          title={landscapeCarousel.title}
          description={landscapeCarousel.description}
          images={landscapeCarousel.images}
        />
        <Box my="16" />
      </Container>
    </div>
  );
};

export default Home;
