import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Button, Container, Flex, Spacer } from "@chakra-ui/react";
import NavBar from "../components/navBar";
import Hero from "../components/hero";
import Carousel from "../components/carousel";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Contenful Chakra</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <Container>
        <Hero
          title="Grasshoppers Academy Content Studio"
          description="Grasshoppers Academy Content Studio (GACS) is an initiative that allows students to build (partial) dynamic websites for real clients."
          cta={{ label: "Documentation", href: "documentation" }}
          image="ontwikkelen-jstack.jpg"
        />
        <Carousel />
      </Container>
    </div>
  );
};

export default Home;
